version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: uxerra
      POSTGRES_PASSWORD: password
      POSTGRES_DB: uxerra_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "4001:4001"
      - "3013:3013"
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  pgdata: 